### ISSUE TITLE
Are there plans to switch to something else from jcenter?

### ISSUE THREAD

**Issue by leoxshn** [appspell/ShaderView#11]
jcenter seems to be at it's end of life, it might be a good idea to switch to another repository

JitPack could work, but I had to do many changed in my fork for it to properly work, so I'm not sure if that's ok

**Comment by leoxshn** [comment]
I made a pull request: #12

**Comment by appspell** [comment]
Jitpack is okay, thank you for the PR! I will publish it there soon

**Comment by appspell** [comment]
@leoxshn Hey Leo,
Is there any chance you could check my comments to the PR?

**Comment by leoxshn** [comment]
I did, I'm working on a new PR

**Comment by leoxshn** [comment]
I made a new PR: #13, I didn't know how to update the first PR, sorry for the inconvenience

**Comment by appspell** [comment]
We've finally migrated!
