### ISSUE TITLE
Surface is invalid when put ShaderView in ViewPager2 and swipe to previous page item

### ISSUE THREAD

**Issue by hvsimon** [appspell/ShaderView#7]
Assume there are two Fragment (`AFragment` and `BFragment`) in ViewPager2.
Each Fragment contains one ShaderView (`AShaderView` and `BShaderView`).

When we swipe the ViewPager2:

`AFragment` -> `BFragment` -> `AFragment`

The Surface is invalid that used by `AShaderView`.

----

My survey:

The first step `AFragment` -> `BFragment` cause the Surface in `AShaderView` been release in

https://github.com/appspell/ShaderView/blob/0573652faf75aee4616e233d53ea858cc0c9e05a/ShaderView/src/main/java/com/appspell/shaderview/gl/params/ShaderParamsImpl.kt#L53-L69
(Called from `onSurfaceTextureDestroyed`)

and the second step `BFragment` -> `AFragment` using the Surface which had been release in the previous step.

It can not create a new Surface because Param.ValueType.SAMPLER_OES value is not null

https://github.com/appspell/ShaderView/blob/0573652faf75aee4616e233d53ea858cc0c9e05a/ShaderView/src/main/java/com/appspell/shaderview/gl/params/ShaderParamsImpl.kt#L161-L177

**Comment by appspell** [comment]
@hvsimon thank you to reporting the issue!

It will be fixed here https://github.com/appspell/ShaderView/pull/10
And added to the next release
